### ISSUE TITLE
RuntimeWarning: invalid value encountered in subtract

### ISSUE THREAD

**Issue by ebadi** [HansjoergW/sec-fincancial-statement-data-set#11]
I've noticed that when I use the pandas describe() method, I receive the following warning:
```
 RuntimeWarning: invalid value encountered in subtract   sqr = _ensure_numeric((avg - values) ** 2)
```

It seems that the issue arises because inf values are somehow being assigned to certain rows in the 'AssetsLiaEquCheck_error', 'GrossOpexpOpil_error', and 'NetCashContOp_error' columns, as can be seen in:  https://github.com/HansjoergW/sec-fincancial-statement-data-set/blob/main/notebooks/07_01_BS_standardizer.ipynb

I am dropping these columns in my personal project,it might be worth documenting what inf means in this case or resolving this bug (if it is indeed an issue) for others who might encounter the same problem.

**Comment by HansjoergW** [comment]
I would recommend dropping all rows with validation categories  100 or also 10. Validation gives an idea about how well the data matches some expected basic rules of the financial statement.

For instance, AssetsLiaEqu checks if "Assets = Liabilities + Equity". This is a basic requirement and of a balance sheet and if you receive an inf value in AssetsLiaEqu Check_error (or a AssetsLiaEqu_cat =100), there is something wrong with the data or the transformation.

**Comment by ebadi** [comment]
Good point.  Didn't know about this. Thanks
