### ISSUE TITLE
CP standardizer : TradingSymbol, SecurityExchangeName

### ISSUE THREAD

**Issue by ebadi** [HansjoergW/sec-fincancial-statement-data-set#12]
Hello,
I tried using the code in the `medium_intro_secfsds.ipynb` notebook to extract the TradingSymbol, SecurityExchangeName from the cover page (`CP` ) statements. 
 
![Screenshot from 2024-08-23 21-51-01](https://github.com/user-attachments/assets/be1c4cf2-3f2e-4f45-80b9-0698dc4752a2)

As you can see in my [jupyter notebook](https://github.com/ebadi/finance-csv-dump/blob/main/medium_intro_secfsds.ipynb) these tags are present in `pre_df`. However when I try to merge it with `num_df` to get their value, I am not successful. From CP statements, I also find other tags such as `EntityCommonStockSharesOutstanding` , `EntityAddressStateOrProvince` to be interesting.  I really hope that I won't need to write a new CP standardizer. 

What is the simplest way to do cik or even adsh to TradingSymbol, SecurityExchangeName lookup? 

In general, it would be great if there was a function (similar to ZipCollector) that without any standardization, we get the columns of data (tags) when we pass 
- a report or a company
- a filter (on column, statement , form ...)
 

### Footnote

I also noticed that the version column in  `num_df` has adsh values!

![image](https://github.com/user-attachments/assets/aa91d417-72bb-41b6-8b0e-f0bf23bebdb2)

**Comment by HansjoergW** [comment]
Hi @ebadi 
The NUM_df, as the name suggests, only contains numeric values. The SEC financial statement data sets (https://www.sec.gov/about/dera_financial-statement-data-set) only contains numeric values. See also the comments in my Medium article (https://medium.com/@hansjoerg.wingeier/understanding-the-sec-financial-statement-data-sets-6148e07d1715) where I describe the "stmt" field for the PRE file:

> stmt: Statement type. This can be BS (Balance Sheet), IS (Income Statement), CF (Cash Flow), EQ (Equity), CI (Comprehensive Income), UN (Unclassifiable Statement), CP (Cover Page). The most important ones are BS, IS, and CF. **You will only find a few CP entries in the Financial Statement Data Sets, since this data set does not include text values.**

If we want "text" data, we would need to use the SEC financial statement and notes data set (https://www.sec.gov/data-research/financial-statement-notes-data-sets). However, this one is about 10 times larger. I might be writing a version 2 of the library somewhen in the future, which will use that larger dataset. But I haven't decided yet.

So bottom line: There is no textual information in the SEC financial statement data set.

However,  the SEC does  maintain a list with cik to Symbol mapping:
- https://www.sec.gov/include/ticker.txt

There is also a python library addressing this, but the last release was over 2 years ago:
- https://sec-cik-mapper.readthedocs.io/en/latest/


The about your footnote:

If you see "adsh" number in the "version" column, it means that the company is not using the definition of the official US-GAAP definition tags. It might be the same name as the official tag, but they might use a somewhat different "definition" of it. That should be mentioned somewhere in the notes of a report.

This is actually, what the `OfficialTagsOnlyXXFilter` filters out.

Fun fact as a side note: The SEC actually trags the "usage" of custom tags on a special page:
https://www.sec.gov/data-research/gaap-xbrl-custom-tags

**Comment by ebadi** [comment]
Thank you for another comprehensive response.
